### PR TITLE
doc: add homebrew install instruction

### PR DESCRIPTION
**Pull request by chenrui333**
fixes 
- #37

relates to:
- Homebrew/homebrew-core#80160

### CODE REVIEW

**Comment by yannh** [comment]
Hi @chenrui333 ! This looks great, though I am quite unfamiliar with brew :) I am mostly wondering how this will be maintained in the future. Can new releases be pushed automatically? What about this approach https://github.com/yannh/kubeconform/pull/40? Thanks a lot!

**Comment by chenrui333** [comment]
yeah, it would be maintained whenever there is a new release, we have maintained the freshness for many other projects as well.

It reminds me that I should add a release badge per this PR as well.

**Comment by chenrui333** [comment]
Answering your question regarding goreleaser for homebrew, we don't need it as it is in the homebrew-core registry now.

**Comment by yannh** [comment]
Ok awesome! Happy to trust you for future updates -  or point people to  https://github.com/Homebrew/homebrew-core/pull/80160  if they want to propose a new version :) Thanks a lot!

**Comment by chenrui333** [comment]
Appreciate the trust. :)

**Comment by chenrui333** [comment]
I also just made couple of changes for the repo as well :)

**Pull request merged**
