### PR TITLE
build: bump to use go1.17

### PR DESCRIPTION
**Pull request by chenrui333**
Update to the [latest go1.17](https://blog.golang.org/go1.17)

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @yannh

**Comment by yannh** [comment]
I'm here @chenrui333 , I could merge it, but it is pretty confusing and I should rework the build system - the "github packages" are build with goreleaser, while the docker image is built and pushed manually... this is updating Go for the docker image, not for the Github release files. 
Options would be:
 * Use a newer goreleaser image and use goreleaser to build the docker image too
 * Build a custom goreleaser image with a fixed go version, so we know what we build with.

I can merge this, I just want to be clear that the build system needs a bit of work.

**Comment by chenrui333** [comment]
This is more like a minor update (trying to stay with the latest go), we dont need to update the build system. Besides, goreleaser is to release the artifacts across the platforms. Let me know if that makes sense.

**Comment by yannh** [comment]
:+1:   Just emphasizing that the binaries released through github releases wont use this just yet :bow:

**Comment by chenrui333** [comment]
yeah, it would happen in the next release. :)

**Comment by yannh** [comment]
@chenrui333 I have updated the Makefile, goreleaser and the CI. 

Now both the Docker Container and the release artifacts are built by goreleaser, and are built using the go binaries from the goreleaser image. This was previously inconsistent - the docker image was using a different build process.

I have added a comment in the Makefile to make clear that the docker-build and docker-build-static targets are only for local development. We could potentially improve this by forcing the go binary used in goreleaser, but I am not sure of the benefit.

**Pull request merged**
