### PR TITLE
support disabling ssl validation in openapi2jsonschema.py

### LINKED ISSUE #157: openapi2jsonschema.py certificate verify failed: unable to get local issuer certificate
Running `python3 ./scripts/openapi2jsonschema.py http://raw.githubusercontent.com/aws/amazon-sagemaker-operator-for-k8s/master/config/crd/bases/sagemaker.aws.amazon.com_trainingjobs.yaml` on MacOS failed with below error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1447, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/openapi2jsonschema.py", line 128, in <module>
    f = urllib.request.urlopen(crdFile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
```

adding below lines at the beginning of the script resolved the issue:

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

There's also a way to disable ssl validation in `urllib` using [this](https://stackoverflow.com/a/58337431/1264304) way. 

If adding `--verify-ssl` script argument (which defaults to `True` ) to `openapi2jsonschema.py`  is an  acceptable solution, i'll open pr.

### PR DESCRIPTION
**Pull request by w7089**
Fixes #157

not the best implementation, but the pr has the minimal changes required in order to run this script on MAC without an issue. If the pr is approved, will edit the README as well

### CODE REVIEW

**Comment by yannh** [comment]
:tada:  Any chance to add an acceptance tests to demonstrate that this works? :pray:

**Comment by w7089** [comment]
> 🎉 Any chance to add an acceptance tests to demonstrate that this works? 🙏

Sure, added and tested. Added an additional commit which speeds up docker build of bats image.

**Comment by yannh** [comment]
Mhhh I guess to properly test this we'd need a host with a broken or self-signed certificate... I'm not going to use this, if it works for you I'm ok to merge it :)

**Comment by w7089** [comment]
Yes, it works for me, thanks) I didn't change the script's behaviour with respect to certificates usage, only allowed to disable CA cert usage when accessing kubernetes yaml CRDs using https. Without this, the script fails on MAC and requires to modify it.

**Pull request merged**
