### PR TITLE
Forbid duplicate keys in strict mode

### PR DESCRIPTION
**Pull request by bilbof**
Prevents specifying duplicate keys using
UnmarshallStrict: https://pkg.go.dev/gopkg.in/yaml.v2#UnmarshalStrict

### CODE REVIEW

**Comment by yannh** [comment]
Loving that :) Think you could add a simple acceptance tests to show it failing here? https://github.com/yannh/kubeconform/blob/master/acceptance.bats

**Comment by bilbof** [comment]
@yannh absolutely -- I've added acceptance tests.

**Comment by yannh** [comment]
Looks like a nice addition, thanks!

**Comment by bilbof** [comment]
Awesome, thanks for the quick approve/merge 👍

**Pull request merged**
