### PR TITLE
feat: exit early on invalid k8s version flag

### PR DESCRIPTION
**Pull request by levenleven**
Exit early if provided kubernetes version is not in expected format.

Resolves https://github.com/yannh/kubeconform/issues/119

### CODE REVIEW

**Comment by yannh** [comment]
I like it, small and nice improvement :) I might add a small acceptance test before merging this.

**Comment by yannh** [comment]
I realised it behaves slightly differently than when passing an incorrect -schema-location - in which case it doesn't print the help, and now I am trying to see if I can implement this using the new flags.TextVar which seems like it could provide an elegant solution, but I've not played with this before :see_no_evil:

**Comment by yannh** [comment]
Raaaah git be damned I guess I messed up somewhere when rebasing, sorry :(  Can you check the last 2 commits and lmk what you think?

**Comment by levenleven** [comment]
LGTM, Thanks!

**Comment by yannh** [comment]
merged https://github.com/yannh/kubeconform/pull/254  :+1:

**Pull request closed without merging**
