### PR TITLE
Add jUnit XML output formatter

### PR DESCRIPTION
**Pull request by cvillers**
I've implemented an output formatter to produce jUnit XML, as it is a _de facto_ standard for reporting test cases in CI systems. Highlights:

* One report file generated per run
* One test suite generated per input file
* Names are formed as below. (I couldn't quite nail it down, but philosophically it feels reasonably correct that the "class" is the kind and the "test case" is the specific object.)
  * Class name: `<kind>@<version>`
  * Test case name: `<namespace>/<name>`
* All test cases are always listed in output regardless of success or failure (same as the TAP formatter)

### CODE REVIEW

**Comment by yannh** [comment]
Hi @cvillers , that's a great contribution! For the test I think it might have been simpler to compare the output to the expected output, rather than comparing individual properties, assuming the output doesnt vary between two runs - would have been a bit shorter and avoided the new dependency. Happy to merge as it though, thx a lot :+1:  :rocket:

**Comment by yannh** [comment]
Added this commit: https://github.com/yannh/kubeconform/commit/77682c31420bc2d9c3373302201beca8c3d93bb6
For the tests to pass.
Output looks like this:
<testsuites name="kubeconform" time="0.000324368" tests="1" failures="0" disabled="0" errors="0">
  <testsuite name="deployment.yml" id="1" tests="1" failures="0" errors="0" disabled="0" skipped="0">
    <properties></properties>
    <testcase name="my-namespace/my-app" classname="Deployment@apps/v1"></testcase>
  </testsuite>
</testsuites>

Thx!

**Comment by cvillers** [comment]
Good catch, thanks. I implemented the tests with the XML parser instead of a string comparison to make it easier to extend the formatter in the future if desired - there are a few elements and attributes it doesn't create at the moment. XML is verbose enough that it seemed it would be a bit easier to follow the test cases that way.

Thanks for merging! 👍

**Comment by davidholsgrove** [comment]
Hi @yannh any eta on cutting a new release of kubeconform? Would be great to have @cvillers junit output in a release 👍

**Comment by yannh** [comment]
Tagged v0.4.7 :+1:

**Comment by davidholsgrove** [comment]
Fantastic thanks @yannh!

**Pull request merged**
